/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integrantes;

import diocesis.DiocesisController;
import diocesis.DiocesisModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import lumisial.LumisialController;
import lumisial.LumisialModel;
import pais.PaisModel;
import servicios.Consultas;
import servicios.InterfazGrafica;
import servicios.Retorno;

/**
 *
 * @author jhon
 */
public class IntegrantesList2 extends javax.swing.JInternalFrame {
    
    

    /**
     * Creates new form IntegrantesList2
     */
    public IntegrantesList2()
    {
        initComponents();
        DiocesisController objDiocesisController = new DiocesisController(); 
        DefaultComboBoxModel comboPaisModel = new DefaultComboBoxModel(objDiocesisController.loadDataCombo());
        comboPaisCod.setModel(comboPaisModel);
        InterfazGrafica.CambiarEstadoElem(panelSelecLumisial, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboOpcion = new javax.swing.JComboBox();
        panelSelecLumisial = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        comboPaisCod = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        comboDiocesisCod = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        comboLumisialCod = new javax.swing.JComboBox();
        btnListar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableIntegrantesList = new javax.swing.JTable();

        setClosable(true);
        setTitle("LISTAR INTEGRANTES");

        jPanel1.setBackground(new java.awt.Color(72, 113, 214));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel2.setBackground(new java.awt.Color(102, 138, 229));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Listar por");

        comboOpcion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboOpcion.setForeground(new java.awt.Color(0, 0, 0));
        comboOpcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Por lumisial", "Por diocesis" }));
        comboOpcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        comboOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOpcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        panelSelecLumisial.setBackground(new java.awt.Color(102, 138, 229));
        panelSelecLumisial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Pais");

        comboPaisCod.setForeground(new java.awt.Color(0, 0, 0));
        comboPaisCod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        comboPaisCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaisCodActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Diocesis");

        comboDiocesisCod.setForeground(new java.awt.Color(0, 0, 0));
        comboDiocesisCod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        comboDiocesisCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiocesisCodActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Lumisial");

        comboLumisialCod.setForeground(new java.awt.Color(0, 0, 0));
        comboLumisialCod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnListar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnListar.setText("listar");
        btnListar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSelecLumisialLayout = new javax.swing.GroupLayout(panelSelecLumisial);
        panelSelecLumisial.setLayout(panelSelecLumisialLayout);
        panelSelecLumisialLayout.setHorizontalGroup(
            panelSelecLumisialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelecLumisialLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(comboPaisCod, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(comboDiocesisCod, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(comboLumisialCod, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(panelSelecLumisialLayout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSelecLumisialLayout.setVerticalGroup(
            panelSelecLumisialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelecLumisialLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelSelecLumisialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPaisCod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(comboDiocesisCod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(comboLumisialCod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 138, 229));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        tableIntegrantesList.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tableIntegrantesList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableIntegrantesList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSelecLumisial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSelecLumisial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOpcionActionPerformed

        int seleccionado = comboOpcion.getSelectedIndex();
        
        switch(seleccionado){
            case 0:
                
                JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE UNA OPCION");
                InterfazGrafica.CambiarEstadoElem(panelSelecLumisial, false);
                
            break;

            case 1:
                
                InterfazGrafica.CambiarEstadoElem(panelSelecLumisial, true);
                
            break;

            case 2:
                
                InterfazGrafica.CambiarEstadoElem(panelSelecLumisial, false);

                panelSelecLumisial.setEnabled(true);
                comboPaisCod.setEnabled(true);
                comboDiocesisCod.setEnabled(true);
                btnListar.setEnabled(true);
                
            break;

        }
        
    }//GEN-LAST:event_comboOpcionActionPerformed

    private void comboPaisCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaisCodActionPerformed

        comboDiocesisCod.removeAllItems();
        comboLumisialCod.removeAllItems();

        PaisModel objPaisModel = (PaisModel)comboPaisCod.getSelectedItem();
        int paisCod = objPaisModel.getPaisCod();


        LumisialController objLumisialController = new LumisialController();
        DefaultComboBoxModel comboDiocesisModel = new DefaultComboBoxModel(objLumisialController.loadDataDiocesisCombo(paisCod));
        comboDiocesisCod.setModel(comboDiocesisModel);
    }//GEN-LAST:event_comboPaisCodActionPerformed

    private void comboDiocesisCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiocesisCodActionPerformed

        if(comboOpcion.getSelectedIndex() != 2){

            DiocesisModel objDiocesisModel = (DiocesisModel)comboDiocesisCod.getSelectedItem();

            if(objDiocesisModel != null){

                int diocesisCod = objDiocesisModel.getDiocesisCod();
                IntegrantesController objIntegrantesController = new IntegrantesController();
                DefaultComboBoxModel comboLumisialModel = new DefaultComboBoxModel(objIntegrantesController.loadDataLumisialCombo(diocesisCod));
                comboLumisialCod.setModel(comboLumisialModel);	
            }
        }
    }//GEN-LAST:event_comboDiocesisCodActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
      
        DefaultTableModel tableModelIntegrantes = new DefaultTableModel();
        tableModelIntegrantes.addColumn("NOMBRE");
        tableModelIntegrantes.addColumn("CARGOS");
        tableModelIntegrantes.addColumn("LUMISIAL");
        tableModelIntegrantes.addColumn("ESTADO CIVIL");

        int seleccionado = comboOpcion.getSelectedIndex();
        String query = "";

        if(seleccionado ==1){

            LumisialModel objLumisialModel = (LumisialModel) comboLumisialCod.getSelectedItem();
            int lumisialCod = objLumisialModel.getLumisialCode();
            query = "SELECT concat_ws(' ',primerNom,segundoNom,primerApe,segundoApe) as nombre,cargos,fk_lumisialCod,"
                            +"fk_estadoCivilCod FROM asistente WHERE active = true and fk_lumisialCod =" + lumisialCod;

        }else{

            //capturar la diocesis
            DiocesisModel objDiocesisModel = (DiocesisModel) comboDiocesisCod.getSelectedItem();
            int diocesisCod = objDiocesisModel.getDiocesisCod();
            query = "SELECT concat_ws(' ',primerNom,segundoNom,primerApe,segundoApe) as nombre,cargos,fk_lumisialCod,fk_estadoCivilCod FROM asistente inte INNER JOIN lumisial lumi "
                            + "ON inte.fk_lumisialCod = lumi.lumisialCod INNER JOIN ciudad ciu "
                            + "ON lumi.fk_ciudadCod = ciu.ciudadCod  INNER JOIN diosesis dio "
                            + "ON ciu.fk_diocesisCod = dio.diosesisCod "
                            + "WHERE "
                            + "inte.active = true AND "
                            + "lumi.active = true AND "
                            + "dio.active = true AND "
                            + "dio.diosesisCod =" + diocesisCod
                            + " order by primerNom";

        }


        Retorno objRetorno = Consultas.listar(query);
        if(!objRetorno.isError()){

            ResultSet response = objRetorno.getResponse();
            try
            {                
                ResultSetMetaData resMetaData = response.getMetaData();
                int cantidadColumnas = resMetaData.getColumnCount();

                while(response.next()){
                    Object[] filas = new Object[cantidadColumnas];

                    for(int index = 0;index < cantidadColumnas; index++){

                        switch(index){

                            //case para el nombre del lumisial
                            case 2:

                                String getLumisialCod = response.getObject(index+1).toString();
                                String lumisialNom = Consultas.lumisialNom(getLumisialCod);
                                filas[index] = lumisialNom;

                            break;

                            //case para el nombre del estado civil
                            case 3:

                                String getestadoCivilCod = response.getObject(index+1).toString();
                                String estadoCivilDesc = Consultas.EstadiCivilDesc(getestadoCivilCod);
                                filas[index] = estadoCivilDesc;

                            break;

                            default:
                                filas[index] = response.getObject(index+1);
                            break;	

                        }

                    }
                    tableModelIntegrantes.addRow(filas);
                }
                tableIntegrantesList.setModel(tableModelIntegrantes);

            } catch (SQLException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
            }

        }else{

            JOptionPane.showMessageDialog(null, objRetorno.getErrorMsg());
        }        
        
        
    }//GEN-LAST:event_btnListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox comboDiocesisCod;
    private javax.swing.JComboBox comboLumisialCod;
    private javax.swing.JComboBox comboOpcion;
    private javax.swing.JComboBox comboPaisCod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelSelecLumisial;
    private javax.swing.JTable tableIntegrantesList;
    // End of variables declaration//GEN-END:variables
}
